#!/bin/sh

# Uncomment the following two lines for normal desktop:
 unset SESSION_MANAGER
  exec /etc/X11/xinit/xinitrc

  [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
  [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
  xsetroot -solid grey
  vncconfig -iconic &
  x-terminal-emulator -geometry 1440x900 -ls -title "$VNCDESKTOP Desktop" &
  #x-window-manager &
  gnome-session &

