subdirs = abort atoi atshm block child client copy crc8 CUnit \
	  CUnit_test execve fdopen fdread fkill getopt localtime \
       	  fstat getname ids killer libcli libcli_test lpudated \
          lpudated-rc lpudated-sig md5lib md5_test mkq mksem mkset \
	  mkshm mmcat mutex newfifo opipe opshm pending piperw popen \
	  prpids qctl qrd qsnd rdfifo receiver resusg1 resusg2 sctl \
	  seek sender server ssctest system thrdcancel thrdcreat \
	  time umask waiter web_client web_server wrfifo message_queues \
	  endian sizeof pointer ttyname pts_write mac_get pcap_header \
	bit

include $(MKDIR)/make.dir

